/**
 * Automatically generated by the bundler. DO NOT EDIT!
 */

export * from "./base/WXClass";
export * from "./Intent";
export * from "./WebUI";
export * from "./WXEvent";
export * from "./WXEventHandler";