export interface WXApplicationInfo {
  getPackageName(): string;
  getName(): string | null;
  getLabel(): string | null;
  getVersionName(): string | null;
  getVersionCode(): number;
  getNonLocalizedLabel(): string | null;
  getAppComponentFactory(): string | null;
  getBackupAgentName(): string | null;
  getCategory(): number;
  getClassName(): string | null;
  getCompatibleWidthLimitDp(): number;
  getCompileSdkVersion(): number;
  getCompileSdkVersionCodename(): string | null;
  getDataDir(): string | null;
  getDescription(): string | null;
  getDeviceProtectedDataDir(): string | null;
  getEnabled(): Boolean;
  getFlags(): number;
  getLargestWidthLimitDp(): number;
  getManageSpaceActivityName(): string | null;
  getMinSdkVersion(): number;
  getNativeLibraryDir(): string | null;
  getPermission(): string | null;
  getProcessName(): string | null;
  getPublicSourceDir(): string | null;
  getRequiresSmallestWidthDp(): number;
  getSharedLibraryFiles(): string | null;
  getSourceDir(): string | null;
  getSplitNames(): string | null;
  getSplitPublicSourceDirs(): string | null;
  getSplitSourceDirs(): string | null;
  getStorageUuid(): string | null;
  getTargetSdkVersion(): number;
  getTaskAffinity(): string | null;
  getTheme(): number;
  getUiOptions(): number;
  getUid(): number;
}
